#ifndef _SCANLINE_H
#define _SCANLINE_H

/*
 * In case a scanline was generated by a polygon with no anti alias
 * the resulting scanlines will have only one span with the same width
 * as the scanline and a coverage of the 100%
 * For anti aliased scanlines each 
 * TODO
 * - each scanline pixel can have different subpixel approximation
 */


#endif
