/* File generated by enesim_generator, don't modify it */
#include "enesim_common.h"
#include "Enesim.h"
#include "enesim_private.h"

static void argb8888_pre_pt_color_blend(Enesim_Surface_Data *d, Enesim_Surface_Data *s, unsigned int color, unsigned char *mask)
{
	unsigned int data0;
	argb8888_pre_from_argb(color, &data0);
	argb8888_pre_blend(d->argb8888_pre.plane0, data0);
}
static void argb8888_pre_pt_pixel_blend_argb8888(Enesim_Surface_Data *d, Enesim_Surface_Data *s, unsigned int color, unsigned char *mask)
{
	unsigned int data0;
	unsigned int argb;
	argb8888_to_argb(&argb, *s->argb8888.plane0);
	argb8888_pre_from_argb(argb, &data0);
	argb8888_pre_blend(d->argb8888_pre.plane0, data0);
}
static void argb8888_pre_pt_pixel_blend_argb8888_pre(Enesim_Surface_Data *d, Enesim_Surface_Data *s, unsigned int color, unsigned char *mask)
{
	unsigned int data0;
	unsigned int argb;
	argb8888_pre_blend(d->argb8888_pre.plane0, data0);
}
static void argb8888_pre_pt_pixel_blend_rgb565(Enesim_Surface_Data *d, Enesim_Surface_Data *s, unsigned int color, unsigned char *mask)
{
	unsigned int data0;
	unsigned int argb;
	rgb565_to_argb(&argb, *s->rgb565.plane0, *s->rgb565.plane1);
	argb8888_pre_from_argb(argb, &data0);
	argb8888_pre_blend(d->argb8888_pre.plane0, data0);
}
static void argb8888_pre_sp_color_blend(Enesim_Surface_Data *d, unsigned int len, Enesim_Surface_Data *s, unsigned int color, unsigned char *mask)
{
	Enesim_Surface_Data dtmp, end;

	argb8888_pre_data_copy(d, &dtmp);
	argb8888_pre_data_offset(d, &end, len);
	while (dtmp.argb8888_pre.plane0 < end.argb8888_pre.plane0)
	{
		argb8888_pre_pt_color_blend(&dtmp, NULL, color, NULL);
		argb8888_pre_data_increment(&dtmp, 1);
	}
}
static void argb8888_pre_sp_pixel_blend_argb8888(Enesim_Surface_Data *d, unsigned int len, Enesim_Surface_Data *s, unsigned int color, unsigned char *mask)
{
	Enesim_Surface_Data stmp, dtmp, end;

	argb8888_pre_data_copy(d, &dtmp);
	argb8888_data_copy(s, &stmp);
	argb8888_pre_data_offset(d, &end, len);
	while (dtmp.argb8888_pre.plane0 < end.argb8888_pre.plane0)
	{
		argb8888_pre_pt_pixel_blend_argb8888(&dtmp, &stmp, 0, NULL);
		argb8888_data_increment(&stmp, 1);
		argb8888_pre_data_increment(&dtmp, 1);
	}
}
static void argb8888_pre_sp_pixel_blend_argb8888_pre(Enesim_Surface_Data *d, unsigned int len, Enesim_Surface_Data *s, unsigned int color, unsigned char *mask)
{
	Enesim_Surface_Data stmp, dtmp, end;

	argb8888_pre_data_copy(d, &dtmp);
	argb8888_pre_data_copy(s, &stmp);
	argb8888_pre_data_offset(d, &end, len);
	while (dtmp.argb8888_pre.plane0 < end.argb8888_pre.plane0)
	{
		argb8888_pre_pt_pixel_blend_argb8888_pre(&dtmp, &stmp, 0, NULL);
		argb8888_pre_data_increment(&stmp, 1);
		argb8888_pre_data_increment(&dtmp, 1);
	}
}
static void argb8888_pre_sp_pixel_blend_rgb565(Enesim_Surface_Data *d, unsigned int len, Enesim_Surface_Data *s, unsigned int color, unsigned char *mask)
{
	Enesim_Surface_Data stmp, dtmp, end;

	argb8888_pre_data_copy(d, &dtmp);
	rgb565_data_copy(s, &stmp);
	argb8888_pre_data_offset(d, &end, len);
	while (dtmp.argb8888_pre.plane0 < end.argb8888_pre.plane0)
	{
		argb8888_pre_pt_pixel_blend_rgb565(&dtmp, &stmp, 0, NULL);
		rgb565_data_increment(&stmp, 1);
		argb8888_pre_data_increment(&dtmp, 1);
	}
}
static void argb8888_pre_sp_pixel_color_blend_argb8888(Enesim_Surface_Data *d, unsigned int len, Enesim_Surface_Data *s, unsigned int color, unsigned char *mask)
{
	Enesim_Surface_Data stmp, dtmp, end;

	argb8888_pre_data_copy(d, &dtmp);
	argb8888_data_copy(s, &stmp);
	argb8888_pre_data_offset(d, &end, len);
	while (dtmp.argb8888_pre.plane0 < end.argb8888_pre.plane0)
	{
		argb8888_pre_pt_pixel_color_blend_argb8888(&dtmp, &stmp, color, NULL);
		argb8888_data_increment(&stmp, 1);
		argb8888_pre_data_increment(&dtmp, 1);
	}
}
static void argb8888_pre_pt_color_fill(Enesim_Surface_Data *d, Enesim_Surface_Data *s, unsigned int color, unsigned char *mask)
{
	unsigned int data0;
	argb8888_pre_from_argb(color, &data0);
	argb8888_pre_fill(d->argb8888_pre.plane0, data0);
}
static void argb8888_pre_pt_pixel_fill_argb8888(Enesim_Surface_Data *d, Enesim_Surface_Data *s, unsigned int color, unsigned char *mask)
{
	unsigned int data0;
	unsigned int argb;
	argb8888_to_argb(&argb, *s->argb8888.plane0);
	argb8888_pre_from_argb(argb, &data0);
	argb8888_pre_fill(d->argb8888_pre.plane0, data0);
}
static void argb8888_pre_pt_pixel_fill_argb8888_pre(Enesim_Surface_Data *d, Enesim_Surface_Data *s, unsigned int color, unsigned char *mask)
{
	unsigned int data0;
	unsigned int argb;
	argb8888_pre_fill(d->argb8888_pre.plane0, data0);
}
static void argb8888_pre_pt_pixel_fill_rgb565(Enesim_Surface_Data *d, Enesim_Surface_Data *s, unsigned int color, unsigned char *mask)
{
	unsigned int data0;
	unsigned int argb;
	rgb565_to_argb(&argb, *s->rgb565.plane0, *s->rgb565.plane1);
	argb8888_pre_from_argb(argb, &data0);
	argb8888_pre_fill(d->argb8888_pre.plane0, data0);
}
static void argb8888_pre_sp_color_fill(Enesim_Surface_Data *d, unsigned int len, Enesim_Surface_Data *s, unsigned int color, unsigned char *mask)
{
	Enesim_Surface_Data dtmp, end;

	argb8888_pre_data_copy(d, &dtmp);
	argb8888_pre_data_offset(d, &end, len);
	while (dtmp.argb8888_pre.plane0 < end.argb8888_pre.plane0)
	{
		argb8888_pre_pt_color_fill(&dtmp, NULL, color, NULL);
		argb8888_pre_data_increment(&dtmp, 1);
	}
}
static void argb8888_pre_sp_pixel_fill_argb8888(Enesim_Surface_Data *d, unsigned int len, Enesim_Surface_Data *s, unsigned int color, unsigned char *mask)
{
	Enesim_Surface_Data stmp, dtmp, end;

	argb8888_pre_data_copy(d, &dtmp);
	argb8888_data_copy(s, &stmp);
	argb8888_pre_data_offset(d, &end, len);
	while (dtmp.argb8888_pre.plane0 < end.argb8888_pre.plane0)
	{
		argb8888_pre_pt_pixel_fill_argb8888(&dtmp, &stmp, 0, NULL);
		argb8888_data_increment(&stmp, 1);
		argb8888_pre_data_increment(&dtmp, 1);
	}
}
static void argb8888_pre_sp_pixel_fill_argb8888_pre(Enesim_Surface_Data *d, unsigned int len, Enesim_Surface_Data *s, unsigned int color, unsigned char *mask)
{
	Enesim_Surface_Data stmp, dtmp, end;

	argb8888_pre_data_copy(d, &dtmp);
	argb8888_pre_data_copy(s, &stmp);
	argb8888_pre_data_offset(d, &end, len);
	while (dtmp.argb8888_pre.plane0 < end.argb8888_pre.plane0)
	{
		argb8888_pre_pt_pixel_fill_argb8888_pre(&dtmp, &stmp, 0, NULL);
		argb8888_pre_data_increment(&stmp, 1);
		argb8888_pre_data_increment(&dtmp, 1);
	}
}
static void argb8888_pre_sp_pixel_fill_rgb565(Enesim_Surface_Data *d, unsigned int len, Enesim_Surface_Data *s, unsigned int color, unsigned char *mask)
{
	Enesim_Surface_Data stmp, dtmp, end;

	argb8888_pre_data_copy(d, &dtmp);
	rgb565_data_copy(s, &stmp);
	argb8888_pre_data_offset(d, &end, len);
	while (dtmp.argb8888_pre.plane0 < end.argb8888_pre.plane0)
	{
		argb8888_pre_pt_pixel_fill_rgb565(&dtmp, &stmp, 0, NULL);
		rgb565_data_increment(&stmp, 1);
		argb8888_pre_data_increment(&dtmp, 1);
	}
}
static void argb8888_pre_sp_pixel_color_fill_argb8888(Enesim_Surface_Data *d, unsigned int len, Enesim_Surface_Data *s, unsigned int color, unsigned char *mask)
{
	Enesim_Surface_Data stmp, dtmp, end;

	argb8888_pre_data_copy(d, &dtmp);
	argb8888_data_copy(s, &stmp);
	argb8888_pre_data_offset(d, &end, len);
	while (dtmp.argb8888_pre.plane0 < end.argb8888_pre.plane0)
	{
		argb8888_pre_pt_pixel_color_fill_argb8888(&dtmp, &stmp, color, NULL);
		argb8888_data_increment(&stmp, 1);
		argb8888_pre_data_increment(&dtmp, 1);
	}
}
Enesim_Drawer argb8888_pre_drawer = {
	.sp_color[ENESIM_BLEND] = argb8888_pre_sp_color_blend,
	.pt_color[ENESIM_BLEND] = argb8888_pre_pt_color_blend,
	.sp_pixel[ENESIM_BLEND][ENESIM_SURFACE_ARGB8888] = argb8888_pre_sp_pixel_blend_argb8888,
	.pt_pixel[ENESIM_BLEND][ENESIM_SURFACE_ARGB8888] = argb8888_pre_pt_pixel_blend_argb8888,
	.sp_pixel[ENESIM_BLEND][ENESIM_SURFACE_ARGB8888_PRE] = argb8888_pre_sp_pixel_blend_argb8888_pre,
	.pt_pixel[ENESIM_BLEND][ENESIM_SURFACE_ARGB8888_PRE] = argb8888_pre_pt_pixel_blend_argb8888_pre,
	.sp_pixel[ENESIM_BLEND][ENESIM_SURFACE_RGB565] = argb8888_pre_sp_pixel_blend_rgb565,
	.pt_pixel[ENESIM_BLEND][ENESIM_SURFACE_RGB565] = argb8888_pre_pt_pixel_blend_rgb565,
	.sp_color[ENESIM_FILL] = argb8888_pre_sp_color_fill,
	.pt_color[ENESIM_FILL] = argb8888_pre_pt_color_fill,
	.sp_pixel[ENESIM_FILL][ENESIM_SURFACE_ARGB8888] = argb8888_pre_sp_pixel_fill_argb8888,
	.pt_pixel[ENESIM_FILL][ENESIM_SURFACE_ARGB8888] = argb8888_pre_pt_pixel_fill_argb8888,
	.sp_pixel[ENESIM_FILL][ENESIM_SURFACE_ARGB8888_PRE] = argb8888_pre_sp_pixel_fill_argb8888_pre,
	.pt_pixel[ENESIM_FILL][ENESIM_SURFACE_ARGB8888_PRE] = argb8888_pre_pt_pixel_fill_argb8888_pre,
	.sp_pixel[ENESIM_FILL][ENESIM_SURFACE_RGB565] = argb8888_pre_sp_pixel_fill_rgb565,
	.pt_pixel[ENESIM_FILL][ENESIM_SURFACE_RGB565] = argb8888_pre_pt_pixel_fill_rgb565,
};
