/* File generated by enesim_generator, don't modify it */
#ifndef SURFACE_RGB565_CORE_H_
#define SURFACE_RGB565_CORE_H_
static inline void rgb565_to_argb(unsigned int *argb, unsigned short int plane0, 
unsigned char plane1)
{
	*argb = ((plane0 & 0x1f) << 3) | ((plane0 & 0x7e0) << 5) | ((plane0 & 0xf800) << 8) | ((plane1 & 0x1f) << 27);
}
static inline void rgb565_from_argb(unsigned int argb, unsigned short int *plane0, 
unsigned char *plane1)
{
}
static inline void rgb565_data_copy(Enesim_Surface_Data *s, Enesim_Surface_Data *d)
{
	d->rgb565.plane0 = s->rgb565.plane0;
	d->rgb565.plane1 = s->rgb565.plane1;
}
static inline void rgb565_data_increment(Enesim_Surface_Data *d, unsigned int len)
{
	d->rgb565.plane0 += len;
	d->rgb565.plane1 += len;
}
static inline void rgb565_data_offset(Enesim_Surface_Data *s, Enesim_Surface_Data *d, unsigned int offset)
{
	d->rgb565.plane0 = s->rgb565.plane0 + offset;
	d->rgb565.plane1 = s->rgb565.plane1 + offset;
}
static inline unsigned char rgb565_data_alpha_get(Enesim_Surface_Data *d)
{
	return (*d->rgb565.plane1 >> 0) & 0x1f;
}
#endif
