/* File generated by enesim_generator, don't modify it */
#ifndef SURFACE_RGB565_CORE_H_
#define SURFACE_RGB565_CORE_H_

static inline void rgb565_data_copy(Enesim_Surface_Data *s, Enesim_Surface_Data *d)
{
	d->rgb565.plane0 = s->rgb565.plane0;
	d->rgb565.plane1 = s->rgb565.plane1;
}
static inline void rgb565_data_increment(Enesim_Surface_Data *d, unsigned int len)
{
	d->rgb565.plane0 += len;
	d->rgb565.plane1 += len;
}
static inline void rgb565_data_offset(Enesim_Surface_Data *s, Enesim_Surface_Data *d, unsigned int offset)
{
	d->rgb565.plane0 = s->rgb565.plane0 + offset;
	d->rgb565.plane1 = s->rgb565.plane1 + offset;
}
static inline unsigned char rgb565_data_alpha_get(Enesim_Surface_Data *d)
{
	return (*d->rgb565.plane1 >> 0) & 0x1f;
}
#endif
