#!/bin/sh
rm -rf ./doc/html ./doc/latex ./doc/man
mkdir -p ./doc/html ./doc/latex ./doc/man 2>/dev/null
doxygen
#cp doc/img/*.png doc/html/
rm -f etc_docs.tar etc_docs.tar.gz
tar -cvf etc_docs.tar doc/html doc/man doc/latex
gzip -9f etc_docs.tar
exit 0
