#!/bin/sh
rm -rf ./doc/html ./doc/latex ./doc/man
mkdir -p ./doc/html ./doc/latex ./doc/man 2>/dev/null
doxygen
#cp doc/img/*.png doc/html/
rm -f eobj_docs.tar eobj_docs.tar.gz
tar -cvf eobj_docs.tar doc/html doc/man doc/latex
gzip -9f eobj_docs.tar
exit 0
