#!/bin/sh
rm -rf ./doc/html ./doc/latex ./doc/man
mkdir -p ./doc/html ./doc/latex ./doc/man 2>/dev/null
doxygen
#cp doc/img/*.png doc/html/
rm -f enginy_docs.tar enginy_docs.tar.gz
tar -cvf enginy_docs.tar doc/html doc/man doc/latex
gzip -9f enginy_docs.tar
exit 0
